name: Generate Context

on:
  push:
    branches: [main]
    
jobs:
  context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create context via lambda
        id: context
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: create-test-scope
          Payload: '{github_url: https://github.com/${{ github.repository }}, upload_to_s3: true}'


