name: Generate Context

on:
  push:
    branches: [main]
    
jobs:
  context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create context from the repo
        env:
          LAMBDA_URL: ${{ secrets.KB_LAMBDA_API_URL }}
          REPO_URL: https://github.com/${{ github.repository }}
        run: |
          echo "Sending repo url to Lambda..."

          curl -X POST "$LAMBDA_URL" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
                    --arg github_url "$REPO_URL" \
                    '{github_url: $github_url, upload_to_s3: true}')"
