name: Generate Repo Context

on:
  push:
    branches: [main]
    
jobs:
  context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install docstring-parser graphviz

      - name: Generate Repo Context
        run: |
          mkdir -p output
          python scripts/generate_context.py

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: hackathon-knowledge-base-v2
          source_dir: 'output'
          destination_dir: ${{ github.event.repository.name }}/

