name: Generate Context

on:
  push:
    branches: [main]

jobs:
  context:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
          
      - name: invoke lamda via aws cli
        run: |
          aws lambda invoke \
            --function-name create-test-scope \
            --payload '{"github_url": "https://github.com/${{ github.repository }}", "upload_to_s3": true}' \
            response.json
