name: Generate Complete Repo Context

on:
  push:
    branches: [main]
    
jobs:
  context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install docstring-parser graphviz

      - name: Generate Repo Context
        run: |
          mkdir -p output
          python scripts/generate_context.py

      - name: Sync output to S3
            uses: jakejarvis/s3-sync-action@v0.5.1
            with:
              args: --acl public-read --delete
            env:
              AWS_S3_BUCKET: hackathon-knowledge-base-v2
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: ${{ secrets.AWS_REGION }}
              SOURCE_DIR: output
              DEST_DIR: ${{ github.event.repository.name }}/
