name: Save PR Diff

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  diff:
    runs-on: ubuntu-latest
    env:
      s3_key: ${{ github.repository }}/${{ github.event.pull_request.number }}/payload.json

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Generate PR diff and payload file
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > pr-diff.txt
          echo "==== PR Diff ===="
          cat pr-diff.txt

          payload_file="payload.json"
          cat <<EOF > $payload_file
          {
            "repositoryUrl": "https://github.com/${{ github.repository }}",
            "repository": "${{ github.repository }}",
            "pr_number": "${{ github.event.pull_request.number }}",
            "pr_description": "${{ github.event.pull_request.body }}",
            "commitSha": "${{ github.sha }}",
            "branch": "${{ github.head_ref }}",
            "diff": $(jq -Rs . < pr-diff.txt)
          }
          EOF


      - name: Upload payload to S3
        run: |
          aws s3 cp payload.json s3://closedaioutput/$s3_key

      - name: Invoke Lambda with S3 URL
        run: |
          aws lambda invoke \
            --function-name create-test-scope \
            --cli-binary-format raw-in-base64-out \
            --payload "{\"path\": \"$s3_key\"}" \
            response.json
