name: Save PR Diff

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate PR diff
        run: |
          echo "Fetching base and head SHAs..."
          git fetch origin ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > pr-diff.txt
          echo "==== PR Diff ===="
          head -n 50 pr-diff.txt # Show just part of it to prevent log flooding

      - name: Send diff to Lambda API
        env:
          LAMBDA_URL: ${{ secrets.LAMBDA_API_URL }}
        run: |
          echo "Reading diff into variable..."
          diff_content=$(cat pr-diff.txt | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')

          echo "Sending to Lambda..."
          payload=$(jq -n \
            --arg pr_number "${{ github.event.pull_request.number }}" \
            --arg repo "${{ github.repository }}" \
            --arg pr_description "${{ github.event.pull_request.body }}" \
            --arg commitSha "${{ github.sha }}" \
            --arg repositoryUrl "https://github.com/${{ github.repository }}" \
            --arg branch "${{ github.head_ref }}" \
            --arg diff "$diff_content" \
            '{
              repository: $repo,
              repositoryUrl: $repositoryUrl,
              pr_number: $pr_number,
              pr_description: $pr_description,
              commitSha: $commitSha,
              branch: $branch,
              diff: $diff
            }')

          echo "$payload" | curl -s -X POST "$LAMBDA_URL" \
            -H "Content-Type: application/json" \
            -d @-
