name: Save PR Diff

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate PR diff
        run: |
          git diff origin/${{ github.event.pull_request.base.ref }}...HEAD > pr-diff.txt
          echo "==== PR Diff ===="
          cat pr-diff.txt

      - name: Send diff to Lambda API
        env:
          LAMBDA_URL: ${{ secrets.LAMBDA_API_URL }}
        run: |
          echo "Sending diff to Lambda..."
          curl -X POST "$LAMBDA_URL" \
            -H "Content-Type: application/json" \
            -d "$(jq -Rs \
                          --arg pr_number \"${{ github.event.pull_request.number }}\" \
                          --arg repo \"${{ github.repository }}\" \
                          --arg pr_description \"${{ github.event.pull_request.body }}\" \
                          --arg commitSha \"${{ github.sha }}\" \
                          --arg repositoryUrl \"https://github.com/${{ github.repository }}\" \
                          --arg branch \"${{ github.head_ref }}\" \
                          '{repository: $repo, repositoryUrl: $repositoryUrl, pr_number: $pr_number, pr_description: $pr_description, commitSha: $commitSha, branch: $branch, diff: .}' < pr-diff.txt)"
