name: Build Vector Store

on:
  push:
    branches: [knowledge]

jobs:
  build-vector-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to include code changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install langchain "langchain_aws>=0.0.1" python-dotenv chromadb boto3

      - name: Create Vector Store
        run: |
          python create_vector_store.py

      - name: Upload vector store as artifact
        uses: actions/upload-artifact@v3
        with:
          name: vector-store
          path: ./chroma_db
